# Generated by Django 2.1.7 on 2019-04-22 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolls',
            old_name='section_no',
            new_name='sec_no',
        ),
        migrations.AddField(
            model_name='capstone_team',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sections',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capstone_team',
            name='capstone_team_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sections',
            name='sec_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='capstone_grades',
            unique_together={('course_id', 'sec_no', 'capstone_team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='capstone_section',
            unique_together={('course_id', 'sec_no', 'project_no')},
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team',
            unique_together={('course_id', 'sec_no', 'capstone_team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team_members',
            unique_together={('course_id', 'sec_no', 'student_email', 'capstone_team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('dept_name', 'dept_head')},
        ),
        migrations.AlterUniqueTogether(
            name='enrolls',
            unique_together={('course_id', 'sec_no', 'student_email')},
        ),
        migrations.AlterUniqueTogether(
            name='exam_grades',
            unique_together={('course_id', 'sec_no', 'student_email', 'exam_no')},
        ),
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('course_id', 'sec_no', 'exam_no')},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('course_id', 'sec_no', 'hw_no')},
        ),
        migrations.AlterUniqueTogether(
            name='homework_grades',
            unique_together={('course_id', 'sec_no', 'student_email', 'hw_no')},
        ),
        migrations.AlterUniqueTogether(
            name='prof_team_members',
            unique_together={('prof_email', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('user', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='sections',
            unique_together={('course_id', 'sec_no')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'email')},
        ),
    ]
