# Generated by Django 2.1.7 on 2019-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0002_auto_20190422_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prof_team_members',
            old_name='team_id',
            new_name='teaching_team_id',
        ),
        migrations.AlterField(
            model_name='capstone_team',
            name='capstone_team_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='prof_team_members',
            unique_together={('prof_email', 'teaching_team_id')},
        ),
    ]
