# Generated by Django 2.1.7 on 2019-04-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0004_auto_20190422_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstone_section',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='capstone_team',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='capstone_team_members',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='enrolls',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='exam_grades',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='homework_grades',
            old_name='sec_no',
            new_name='course_section',
        ),
        migrations.AlterUniqueTogether(
            name='capstone_grades',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='capstone_section',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='capstone_section',
            unique_together={('course_section', 'project_no')},
        ),
        migrations.RemoveField(
            model_name='capstone_team',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team',
            unique_together={('course_section', 'capstone_team_id')},
        ),
        migrations.RemoveField(
            model_name='capstone_team_members',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team_members',
            unique_together={('course_section', 'student_email', 'capstone_team_id')},
        ),
        migrations.RemoveField(
            model_name='enrolls',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='enrolls',
            unique_together={('course_section', 'student_email')},
        ),
        migrations.RemoveField(
            model_name='exam_grades',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='exam_grades',
            unique_together={('course_section', 'student_email', 'exam_no')},
        ),
        migrations.RemoveField(
            model_name='exams',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('course_section', 'exam_no')},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('course_section', 'hw_no')},
        ),
        migrations.RemoveField(
            model_name='homework_grades',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='homework_grades',
            unique_together={('course_section', 'student_email', 'hw_no')},
        ),
        migrations.RemoveField(
            model_name='capstone_grades',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='capstone_grades',
            name='sec_no',
        ),
    ]
