# Generated by Django 2.1.7 on 2019-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstone_section',
            name='sponsor_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='prof_team',
            field=models.ForeignKey(null=True, on_delete=None, to='coursesystem.Prof_teams'),
        ),
    ]
