# Generated by Django 2.1.7 on 2019-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0002_auto_20190422_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstone_grades',
            name='capstone_grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exam_grades',
            name='exam_grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homework_grades',
            name='hw_grade',
            field=models.FloatField(),
        ),
    ]
