# Generated by Django 2.1.7 on 2019-04-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0003_auto_20190422_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capstone_section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='capstone_team_members',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exam_grades',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='homework_grades',
            unique_together=set(),
        ),
    ]
