# Generated by Django 2.1.7 on 2019-04-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0004_auto_20190422_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_grades',
            name='exam_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesystem.Exams'),
        ),
    ]
