# Generated by Django 2.1.7 on 2019-04-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0005_auto_20190422_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capstone_section',
            unique_together={('course_section', 'project_no')},
        ),
    ]
