# Generated by Django 2.1.7 on 2019-04-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0007_auto_20190423_1141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together=set(),
        ),
    ]
