# Generated by Django 2.1.7 on 2019-04-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0010_auto_20190423_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('course_section', 'exam_no')},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('course_section', 'hw_no')},
        ),
    ]
