# Generated by Django 2.1.7 on 2019-04-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesystem', '0011_auto_20190423_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_grades',
            name='exam_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursesystem.Exams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework_grades',
            name='hw_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursesystem.Homework'),
            preserve_default=False,
        ),
    ]
